server:
    port: 8081
    error:
        include-message: always
    
eureka:
    instance:
        preferIpAddress: true
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
            
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/school_db
    username: root
    password: password
  jpa:
    hibernate.ddl-auto: update 

keycloak:
  realm:
    name: master
  server:
    url: http://localhost:8080
  clientId: admin-cli
  username: admin
  password: admin